# -*- coding: utf-8 -*-
"""Projeto_PP_16.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oOx9OqVJlE3NNEV46Dt8ZQu3S2HQ967F
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Define um estilo visual mais agradável para os gráficos
sns.set_theme(style="whitegrid")

try:
    # Carrega os resultados do benchmark a partir do arquivo CSV
    df = pd.read_csv("benchmark_results_final.csv")

    # --- Cálculo de Speedup e Eficiência ---
    # Encontra o tempo base (menor número de processos) para cada tamanho de matriz
    df_sorted = df.sort_values(by=["Tamanho(M)", "Processos(P)"])
    baseline_times = df_sorted.groupby("Tamanho(M)")["Tempo(s)"].transform("first")

    # Calcula o Speedup
    df["Speedup"] = baseline_times / df["Tempo(s)"]

    # Calcula a Eficiência
    df["Eficiencia"] = df["Speedup"] / df["Processos(P)"]

    # --- IMPRESSÃO DA TABELA DE DADOS ---
    print("=========================================")
    print("    Tabela de Dados do Benchmark")
    print("=========================================")
    # Usamos to_string() para garantir que a tabela inteira seja impressa
    print(df.to_string())
    print("\n") # Adiciona uma linha em branco para separar a tabela dos logs dos gráficos


    # --- Gráfico 1: Tamanho da Matriz vs. Tempo de Execução (NOVA VISUALIZAÇÃO) ---
    plt.figure(figsize=(10, 6))
    plot_tempo = sns.lineplot(
        data=df,
        x="Tempo(s)",
        y="Tamanho(M)",
        hue="Processos(P)",  # Cores diferentes para cada número de processos
        style="Processos(P)", # Estilos de linha diferentes
        markers=True,
        dashes=False,
        palette="viridis", # Paleta de cores
        legend="full"
    )
    plot_tempo.set_title("Tamanho da Matriz vs. Tempo de Execução", fontsize=16)
    plot_tempo.set_xlabel("Tempo de Execução (segundos)", fontsize=12)
    plot_tempo.set_ylabel("Tamanho da Matriz (Linhas M)", fontsize=12)
    plot_tempo.grid(True, which="both", linestyle="--", linewidth=0.5)
    plt.yticks(df["Linhas(M)"].unique()) # Garante que todos os tamanhos de matriz apareçam no eixo Y
    # Converte o tipo da coluna de processos para string para a legenda ficar correta
    handles, labels = plot_tempo.get_legend_handles_labels()
    plot_tempo.legend(handles=handles, labels=labels, title="Nº de Processos (P)")
    plt.tight_layout()
    plt.savefig("matriz_vs_tempo.png")
    print("Gráfico 'matriz_vs_tempo.png' gerado com sucesso.")


    # --- Gráfico 2: Speedup vs. Número de Processos ---
    plt.figure(figsize=(10, 6))
    plot_speedup = sns.lineplot(
        data=df,
        x="Processos(P)",
        y="Speedup",
        hue="Tamanho(M)",
        style="Tamanho(M)",
        markers=True,
        dashes=False,
        palette="plasma",
        legend="full"
    )
    plot_speedup.set_title("Speedup vs. Número de Processos", fontsize=16)
    plot_speedup.set_xlabel("Número de Processos (P)", fontsize=12)
    plot_speedup.set_ylabel("Speedup", fontsize=12)
    plot_speedup.grid(True, which="both", linestyle="--", linewidth=0.5)
    plt.xticks(df["Processos(P)"].unique())
    plt.legend(title="Tamanho da Matriz (M x N)")
    plt.tight_layout()
    plt.savefig("speedup.png")
    print("Gráfico 'speedup.png' gerado com sucesso.")


    # --- Gráfico 3: Eficiência vs. Número de Processos ---
    plt.figure(figsize=(10, 6))
    plot_eficiencia = sns.lineplot(
        data=df,
        x="Processos(P)",
        y="Eficiencia",
        hue="Tamanho(M)",
        style="Tamanho(M)",
        markers=True,
        dashes=False,
        palette="cividis",
        legend="full"
    )
    plot_eficiencia.set_title("Eficiência vs. Número de Processos", fontsize=16)
    plot_eficiencia.set_xlabel("Número de Processos (P)", fontsize=12)
    plot_eficiencia.set_ylabel("Eficiência", fontsize=12)
    plot_eficiencia.grid(True, which="both", linestyle="--", linewidth=0.5)
    plot_eficiencia.set_ylim(0, 1.1)  # Limite do eixo Y de 0 a 1.1 (para ver 100% de eficiência)
    plt.xticks(df["Processos(P)"].unique())
    plt.legend(title="Tamanho da Matriz (M x N)")
    plt.tight_layout()
    plt.savefig("eficiencia.png")
    print("Gráfico 'eficiencia.png' gerado com sucesso.")

except FileNotFoundError:
    print("Erro: O arquivo 'benchmark_results.csv' não foi encontrado.")
    print("Execute primeiro o script 'Benchmark.sh' para gerar o arquivo de dados.")
except Exception as e:
    print(f"Ocorreu um erro inesperado: {e}")